version: '3.7'

services:
  database_cars:
    image: postgres
    container_name: database_cars
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=estudos
      - POSTGRES_DB=cars
    volumes:
      - pgdata:/data/ 

  app:
    build: .
    container_name: cars
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database_cars
    depends_on:
      - database_cars   

volumes:
  pgdata:
    driver: local